# nginx.conf
worker_processes auto; # 1 ) quantité du processeur (vcpu)

events {#2 réseau par défeaut
    worker_connections 1024;#3)le nombre de fichier  max ouvert en même temps 
}

http {#4déclaration communication interne http 
    include /etc/nginx/mime.types;#5)assimilation des langages par nginx
    
    # Sécurité : On cache la version d'Nginx pour limiter les infos aux hackers
    server_tokens off;#6on cahce la version du logiciel nginx 

    server {#7 comportemnt du serveur après communication avec  le conteneur 
        # Render écoute le port 10000 par défaut
        listen 10000;#8attribution d'une même origine à tout le  container ( juste un port n'est pas un l'origin)

        # 
        location / {#9 manifestation  du reverse prosy pour le diriger sur le front end 
            root /usr/share/nginx/html;#10 redirection vers les pages html grâce à des chemins par défeaut ui  ne sont pas vu à l'extérieur 
            index index.html;#11 récupération de page d'acceuil 
            try_files $uri $uri/ /index.html;#12 Dirigement des par rapport au choix de l'utilisateur quel pages il aura grâce au chemen d'un ficheir , d'un dossier ou sinon de la page d'acceuil
        }

        


# 2. Gestion du Backend (Le Proxy)
        location /api/ {
            # On redirige vers le port interne de ton Backend
            proxy_pass http://127.0.0.1:5000/; 
            
            # On transmet l'IP réelle de l'utilisateur au backend
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeout : Si le back ne répond pas en 30s, on coupe (protection CPU)
            proxy_read_timeout 30s;
            proxy_connect_timeout 30s;
        }
    }
}
