# nginx.conf
worker_processes auto; # 1 ) quantité du processeur (vcpu)

events {#2 réseau par défeaut
    worker_connections 1024;#3)le nombre de fichier  max ouvert en même temps 
}

http {#4déclaration communication interne http 
    include /etc/nginx/mime.types;#5)assimilation des langages par nginx
    
    # Sécurité : On cache la version d'Nginx pour limiter les infos aux hackers
    server_tokens off;#6on cahce la version du logiciel nginx 

    server {#7 comportemnt du serveur après communication avec  le conteneur 
        # Render écoute le port 10000 par défaut
        listen 10000;#8attribution d'une même origine à tout le  container ( juste un port n'est pas un l'origin)

        # 
        location /static {#9 manifestation  du reverse prosy pour le diriger sur le front end , si je met api à la fin de ce chemn la drective va permettre l'addiion non commutative des chemins dont le chemin 1 sera à la fin 
            root /app/ecole_app/; #10 je demande à chercher les pages html dans le dossier static car c'est là où sont ces fichiers par rapport à la création du dossier racine dans le docker 
            index page_1_frontend.html; #Je choisis de mettre ce nom de ficheir car ma page d'acceuil et donc tous mes fichier html se trouvé dans le dossier static
            try_files $uri $uri/ /page_1_frontend.html;  }

        


# 2. Gestion du Backend (Le Proxy)
        location /{
            # On redirige vers le port interne de ton Backend
            proxy_pass http://127.0.0.1:5000/; 
            
            # On transmet l'IP réelle de l'utilisateur au backend
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeout : Si le back ne répond pas en 30s, on coupe (protection CPU)
            proxy_read_timeout 30s;
            proxy_connect_timeout 30s;
        }
    }
}
